project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Rodrigues"
  navbar:
    background: "#abc9db" 
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - papers.qmd
      - posts.qmd
    tools:
      - icon: github
        menu:
          - text: Profile
            href:  https://github.com/gabrielvpina
          - text: Source Code
            href:  https://github.com/gabrielvpina/myBlog


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    resources: 
      - fonts/

execute:
  freeze: auto 



